import { FlightEvent, Provider } from "../providers/types.js";
export type ProviderId = Provider | "generic";
export type Confidence = "high" | "medium" | "low";
export type SourceKind = "file" | "directory" | "git" | "unknown";
export type SourceType = "transcript" | "git" | "hook" | "unknown";
export type Outcome = "success" | "failed" | "unknown";
export type SessionRecord = {
  id: string;
  provider: ProviderId;
  providerLabel: string;
  sourcePath: string;
  sourceKind: SourceKind;
  sourceType?: SourceType;
  createdAt?: string;
  updatedAt?: string;
  indexedAt?: string;
  projectPath?: string;
  projectName?: string;
  projectId?: string;
  projectRoot?: string;
  projectDisplayName?: string;
  title?: string;
  firstPrompt?: string;
  outcome?: Outcome;
  changedFileCount?: number;
  changedFiles?: string[];
  model?: string;
  durationMs?: number;
  failureSummary?: string;
  tokenCount?: number;
  inputTokenCount?: number;
  outputTokenCount?: number;
  cacheTokenCount?: number;
  cacheCreationTokenCount?: number;
  cacheReadTokenCount?: number;
  reasoningTokenCount?: number;
  costUsd?: number;
  sourceHash?: string;
  sourceSize?: number;
  sourceMtimeMs?: number;
  firstEventAt?: string;
  lastEventAt?: string;
  eventCount: number;
  repoRoots: string[];
  repoIds: string[];
  taskSegmentIds: string[];
  commandCount: number;
  failedCommandCount: number;
  fileEventCount: number;
  warningCount: number;
  fingerprint: { sizeBytes?: number; modifiedAt?: string; hash?: string };
  confidence: Confidence;
  warnings: string[];
};
export type TaskSegmentRecord = {
  id: string;
  sessionId: string;
  provider: ProviderId;
  title: string;
  summary?: string;
  startEventIndex: number;
  endEventIndex: number;
  firstEventAt?: string;
  lastEventAt?: string;
  repoRoots: string[];
  repoIds: string[];
  eventCount: number;
  commandCount: number;
  failedCommandCount: number;
  changedFiles: string[];
  confidence: Confidence;
  boundaryReason: string;
  warnings: string[];
};
export type RepoRecord = {
  id: string;
  root: string;
  name: string;
  remote?: string;
  branch?: string;
  sessionIds: string[];
  taskSegmentIds: string[];
  lastEventAt?: string;
};
export type SessionIndex = {
  version: 1;
  generatedAt: string;
  sessions: SessionRecord[];
  taskSegments: TaskSegmentRecord[];
  repos: RepoRecord[];
  warnings: string[];
};
export type DiscoveryOptions = {
  roots?: string[];
  since?: string;
  limit?: number;
};
export type DiscoveredSession = {
  provider: ProviderId;
  sourcePath: string;
  sourceKind: "file" | "directory";
  confidence: Confidence;
  reason: string;
};
export type ProviderAdapter = {
  id: ProviderId;
  label: string;
  discover(options: DiscoveryOptions): Promise<DiscoveredSession[]>;
  parse(discovered: DiscoveredSession): Promise<{
    events: FlightEvent[];
    warnings: string[];
    sessionId?: string;
    cwd?: string;
    provider: ProviderId;
    sourcePath: string;
    startedAt?: string;
    endedAt?: string;
    model?: string;
  }>;
};
